# GD32VF103 Platform Configuration
# GigaDevice GD32VF103 RISC-V microcontroller

[isa]
name = "riscv32imac"

[isa.instruction_timings]
alu = 1
load = 2
store = 2
branch = 2
multiply = 3
divide = 35

[core]
name = "bumblebee-rv32imac"

[core.pipeline]
stages = 2
pipeline_type = "inorder"

[core.cache]
# No cache

[core.memory]
load_buffer_size = 2
store_buffer_size = 2

[core.memory.memory_latency]
type = "fixed"
cycles = 2

[soc]
name = "gd32vf103"
cpu_frequency_mhz = 108

[[soc.memory_regions]]
name = "flash"
start = 0x08000000
size = 131072
latency = 2

[[soc.memory_regions]]
name = "sram"
start = 0x20000000
size = 32768
latency = 1

[board]
name = "gd32vf103c-start"
