# i.MX RT1062 EVK Platform Configuration
# NXP i.MX RT1062 ARM Cortex-M7 crossover MCU

[isa]
name = "armv7e-m"

[isa.instruction_timings]
alu = 1
load = 1
store = 1
branch = 1
multiply = 1
divide = 2

[core]
name = "cortex-m7"

[core.pipeline]
stages = 6
pipeline_type = "inorder"

[core.cache]
[core.cache.instruction_cache]
size_kb = 32
line_size_bytes = 32
associativity = 4
replacement_policy = "LRU"
hit_latency = 0
miss_latency = 8

[core.cache.data_cache]
size_kb = 32
line_size_bytes = 32
associativity = 4
replacement_policy = "LRU"
hit_latency = 0
miss_latency = 8

[core.memory]
load_buffer_size = 4
store_buffer_size = 4

[core.memory.memory_latency]
type = "fixed"
cycles = 2

[soc]
name = "mimxrt1062"
cpu_frequency_mhz = 600

[[soc.memory_regions]]
name = "itcm"
start = 0x00000000
size = 262144
latency = 0

[[soc.memory_regions]]
name = "dtcm"
start = 0x20000000
size = 262144
latency = 0

[[soc.memory_regions]]
name = "ocram"
start = 0x20200000
size = 524288
latency = 1

[board]
name = "mimxrt1062-evk"
