# STM32H743 Nucleo Platform Configuration
# STM32H743ZIT6 ARM Cortex-M7 high-performance microcontroller

[isa]
name = "armv7e-m"

[isa.instruction_timings]
alu = 1
load = 1
store = 1
branch = 1
multiply = 1
divide = 3

[core]
name = "cortex-m7"

[core.pipeline]
stages = 6
pipeline_type = "inorder"

[core.cache]
[core.cache.instruction_cache]
size_kb = 16
line_size_bytes = 32
associativity = 4
replacement_policy = "LRU"
hit_latency = 0
miss_latency = 8

[core.cache.data_cache]
size_kb = 16
line_size_bytes = 32
associativity = 4
replacement_policy = "LRU"
hit_latency = 0
miss_latency = 8

[core.memory]
load_buffer_size = 4
store_buffer_size = 4

[core.memory.memory_latency]
type = "fixed"
cycles = 2

[soc]
name = "stm32h743"
cpu_frequency_mhz = 480

[[soc.memory_regions]]
name = "flash"
start = 0x08000000
size = 2097152
latency = 4

[[soc.memory_regions]]
name = "itcm"
start = 0x00000000
size = 65536
latency = 0

[[soc.memory_regions]]
name = "dtcm"
start = 0x20000000
size = 131072
latency = 0

[[soc.memory_regions]]
name = "sram"
start = 0x24000000
size = 524288
latency = 0

[board]
name = "nucleo-h743zi"
