# STM32F429 Discovery Platform Configuration
# STM32F429ZIT6 ARM Cortex-M4F development board with LCD

[isa]
name = "armv7e-m"

[isa.instruction_timings]
alu = 1
load = 2
store = 2
branch = 1
multiply = 1
divide = 3

[core]
name = "cortex-m4f"

[core.pipeline]
stages = 3
pipeline_type = "inorder"

[core.cache]
# ART Accelerator provides flash prefetch

[core.memory]
load_buffer_size = 2
store_buffer_size = 2

[core.memory.memory_latency]
type = "fixed"
cycles = 2

[soc]
name = "stm32f429"
cpu_frequency_mhz = 180

[[soc.memory_regions]]
name = "flash"
start = 0x08000000
size = 2097152
latency = 2

[[soc.memory_regions]]
name = "sram"
start = 0x20000000
size = 262144
latency = 0

[board]
name = "stm32f429i-disco"
