# STM32F746G Discovery Platform Configuration
# STM32F746NGH6 ARM Cortex-M7 development board

[isa]
name = "armv7e-m"

[isa.instruction_timings]
alu = 1
load = 2
store = 2
branch = 1
multiply = 1
divide = 3

[core]
name = "cortex-m7"

[core.pipeline]
stages = 6
pipeline_type = "inorder"

[core.cache]
[core.cache.instruction_cache]
size_kb = 4
line_size_bytes = 32
associativity = 2
replacement_policy = "LRU"
hit_latency = 0
miss_latency = 8

[core.cache.data_cache]
size_kb = 4
line_size_bytes = 32
associativity = 2
replacement_policy = "LRU"
hit_latency = 0
miss_latency = 8

[core.memory]
load_buffer_size = 4
store_buffer_size = 4

[core.memory.memory_latency]
type = "fixed"
cycles = 2

[soc]
name = "stm32f746"
cpu_frequency_mhz = 216

[[soc.memory_regions]]
name = "flash"
start = 0x08000000
size = 1048576
latency = 2

[[soc.memory_regions]]
name = "itcm"
start = 0x00000000
size = 16384
latency = 0

[[soc.memory_regions]]
name = "dtcm"
start = 0x20000000
size = 65536
latency = 0

[[soc.memory_regions]]
name = "sram"
start = 0x20010000
size = 327680
latency = 0

[board]
name = "stm32f746g-disco"
