# STM32F4 SoC Configuration
# STM32F407/F417 family

name = "stm32f4"
cpu_frequency_mhz = 168

[[memory_regions]]
name = "Flash"
start = 0x08000000
size = 1048576  # 1MB
latency = 5

[[memory_regions]]
name = "SRAM1"
start = 0x20000000
size = 114688  # 112KB
latency = 0

[[memory_regions]]
name = "SRAM2"
start = 0x2001C000
size = 16384  # 16KB
latency = 0

[[memory_regions]]
name = "CCM"
start = 0x10000000
size = 65536  # 64KB
latency = 0
