# Cortex-M4 Core Configuration

name = "cortex-m4"

[pipeline]
stages = 3
pipeline_type = "inorder"

[cache.instruction_cache]
size_kb = 16
line_size_bytes = 32
associativity = 4
replacement_policy = "LRU"
hit_latency = 1
miss_latency = 10

[memory]
load_buffer_size = 4
store_buffer_size = 4

[memory.memory_latency]
type = "fixed"
cycles = 10
